sudo: required
dist: trusty
language: java
jobs:
  include:
    - name: oap-cache-oap
      before_install:
      - sudo apt-get install cmake
      - sudo apt-get install libpthread-stubs0-dev
      - sudo apt-get install libnuma-dev
      install:
      - # Download spark 2.4.4
      - "[ -f spark ] || mkdir spark && cd spark && wget http://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz && cd .."
      - "tar -xf ./spark/spark-2.4.4-bin-hadoop2.7.tgz"
      - "export SPARK_HOME=`pwd`/spark-2.4.4-bin-hadoop2.7"
      before_script:
      - cd /tmp
      - git clone https://github.com/memkind/memkind.git
      - cd memkind && ./build.sh
      - make
      - sudo make install
      - cd ${TRAVIS_BUILD_DIR}
      script:
      - cd ${TRAVIS_BUILD_DIR}/oap-cache/oap/
      - mvn clean -q -Ppersistent-memory test
    - name: oap-shuffle-remote-shuffle
      script:
      - cd ${TRAVIS_BUILD_DIR}/oap-shuffle/remote-shuffle/
      - mvn -q test



